name: Run Discord Bot

on:
  schedule:
    - cron: '*/30 * * * *'  # Chạy mỗi 30 phút
  workflow_dispatch:  # Cho phép kích hoạt thủ công

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install ffmpeg
      run: |
        sudo apt update
        sudo apt install -y ffmpeg

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run bot
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
      run: |
        python botdis.py
